Repository heal-mate/health-friends-server, pull requests merged in 2023-12, with the labels that each got.

#11 Feat: #3 추천 유저 목록 api 구현
  src/models/schemas/match.ts
  src/models/schemas/user.ts
  src/services/matchService.ts
  src/services/userService.ts
Labels: enhancement

#14 Feat: alert crud api 구현
  src/controllers/alertController.ts
  src/controllers/matchController.ts
  src/models/index.ts
  src/models/schemas/alert.ts
  src/routes/alertRouter.ts
  src/routes/index.ts
  src/services/alertService.ts
  src/services/matchService.ts
Labels: enhancement

#12 Feat: #7 마이페이지 수정 및 받아오기 API 구현
  .husky/pre-commit
  src/controllers/userController.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: enhancement

#13 Feat: #8 메이트찾기 조건 API연결
  src/controllers/userController.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: enhancement

#15 Feat: user registr, login api 구현
  .env.sample
  package.json
  src/config/constants.ts
  src/controllers/userController.ts
  src/index.ts
  src/middleware/authJWT.ts
  src/middleware/errorHandler.js
  src/models/index.ts
  src/models/schemas/auth.ts
  src/models/schemas/user.ts
  src/routes/userRouter.ts
  src/services/userService.ts
  src/utils/jwt.ts
  yarn.lock
Labels: enhancement

#16 Feat/login
  .env.sample
  package.json
  src/controllers/alertController.ts
  src/controllers/matchController.ts
  src/controllers/userController.ts
  src/index.ts
  src/middleware/authJWT.ts
  src/models/schemas/user.ts
  src/routes/alertRouter.ts
  src/routes/index.ts
  src/routes/userRouter.ts
  src/services/alertService.ts
  src/services/matchService.ts
  src/services/userService.ts
  yarn.lock
Labels: enhancement

#24 로그아웃, 회원탈퇴 구현 및 리팩터링
  package.json
  src/controllers/authController.ts
  src/controllers/userController.ts
  src/middleware/authJWT.ts
  src/middleware/errorHandler.js
  src/routes/authRouter.ts
  src/routes/index.ts
  src/routes/userRouter.ts
  src/services/alertService.ts
  src/services/authService.ts
  src/services/userService.ts
  src/utils/documentQueryFn.ts
Labels: enhancement

#25 Feat/error
  src/controllers/alertController.ts
  src/controllers/authController.ts
  src/controllers/matchController.ts
  src/controllers/userController.ts
  src/index.ts
  src/middleware/asyncHandler.ts
  src/middleware/authJWT.ts
  src/middleware/errorHandler.js
  src/middleware/errorHandler.ts
  src/middleware/logHandler.ts
  src/services/authService.ts
  src/services/matchService.ts
  src/services/userService.ts
Labels: enhancement

#27 Fix: 웹 푸시 수신자 정상화
  src/controllers/matchController.ts
  src/services/matchService.ts
  src/services/userService.ts
Labels: invalid

#31 Feat: 유효한 유저인지 확인하는 api 추가
  src/controllers/authController.ts
  src/routes/authRouter.ts
  src/services/authService.ts
Labels: enhancement

#36 Feat: #35 유저스키마에 kakaoId 프로퍼티 추가
  src/models/schemas/user.ts
  src/services/authService.ts
  src/services/userService.ts
Labels: enhancement

#37 Fix: 탈퇴한 회원이 재가입이 가능하도록 수정, 비밀번호 암호화 util함수로 분리
  src/services/authService.ts
  src/utils/getHashedPassword.ts
Labels: bug

#39 Feat: 비밀번호 변경 API추가 및 회원가입 성공시 auth db에서 인증정보 삭제
  src/controllers/authController.ts
  src/services/authService.ts
Labels: enhancement

#43 Feat: #40 비밀번호 변경 로직 수정(이메일로 유저 찾기)
  src/controllers/authController.ts
  src/routes/authRouter.ts
  src/services/authService.ts
Labels: enhancement

#44 Feat: #40 비밀번호 변경 시 이메일 인증번호 보내기 기능 로직 수정(회원가입되어있는 유저도 인증번호 받을 수 있게)
  src/controllers/authController.ts
  src/services/authService.ts
Labels: enhancement
